### ISSUE TITLE
팀 리스트 페이지 QA

### ISSUE THREAD

**Issue by M1zz** [ProjectInTheClass/TeamNine#55]
- [ ] 셀의 그림이 기획과 다름

**Comment by hyunjuuun** [comment]
- [ ] 경기 시작 시간 00:00 단위로 출력

- [ ] 장소 출력

- [ ] 초보, 중수, 고수 (참여 난이도) 출력

- [ ] 남은 자리 출력

- [ ] 클릭 시 사용자 페이지로 이동

- [ ] 상단에 팀구하기 / 오른쪽 상단에 종목, 날짜 필터
