### ISSUE TITLE
팀 구하기 페이지 QA

### ISSUE THREAD

**Issue by M1zz** [ProjectInTheClass/TeamNine#56]

**Comment by hyunjuuun** [comment]
- [ ] 경기 종료 시간도 사용자가 설정할 수 있도록 합니다. (현재는 경기 시간 단위를 고르도록 되어 있음)

- [ ] 사용자의 갤러리에서 이미지를 바로 첨부할 수 있도록 합니다.

- [ ] 이미지(필수 x), 경기 장소, 경기 시작 시간, 경기 종료 시간, 종목, 모집인원, 추가 설명으로 구성합니다.
